spring.application.name=crimeArchive
#Show sql queries
spring.jpa.show-sql=true
#create table automatic, understand flyway operartion and change this to validate
spring.jpa.hibernate.ddl-auto=update
minio.endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=bevis
