spring.application.name=crimeArchive
#Show sql queries
spring.jpa.show-sql=true
#create table automatic, understand flyway operartion and change this to validate
spring.jpa.hibernate.ddl-auto=update
minio.endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.bucket=crime-archive
#oauth client repository dependency
#spring.security.oauth2.client.registration.github.client-id=
#spring.security.oauth2.client.registration.github.client-secret=
# keep container alive between restarts
spring.docker.compose.lifecycle-management=start_only
# Debug trace
logging.level.org.springframework.security=debug
